plugins: ['prettier-plugin-astro', 'prettier-plugin-svelte']

useTabs: true
singleQuote: true
overrides:
  - files: '*.astro'
    options:
      semi: true
      parser: 'astro'
      printWidth: 80
  - files: ['*.json', '*.yaml']
    options:
      useTabs: false
